// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoaztlmqqevlbrfypnxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYXp0bG1xcWV2bGJyZnlwbnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjAyNzEsImV4cCI6MjA3MDg5NjI3MX0.hbSNcnjv_OThuDqWwfsmCNBClFOwKRMOirnYWCG-Yts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});